name: Delete New Relic Synthetic Monitor

on:
  push:
    paths:
      - seleniumScriptTeacher.js

jobs:
  delete-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete New Relic Synthetic Monitor
        env:
          API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          API_ENDPOINT: ${{ secrets.NEW_RELIC_API_ENDPOINT }}
          MONITOR_ID: ${{ secrets.MONITOR_ID }}
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" -X DELETE \
            -H "Api-Key:$API_KEY" \
            "$API_ENDPOINT/v3/monitors/$MONITOR_ID")

          if [ "$response" -eq 204 ]; then
            echo "New Relic monitor deleted successfully."
          else
            echo "Failed to delete the New Relic monitor. Response:"
            cat response.json
            exit 1
          fi
