name: Update New Relic Synthetic Monitor Scripts

on:
  push:
    branches:
      - qa
      - stage
      - dev
    paths:
      - seleniumScriptTeacher.js
      - seleniumScriptStudent.js

jobs:
  update-monitor-scripts:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'qa' ||  github.ref == 'refs/heads/stage' && 'stage' ||  github.ref == 'refs/heads/dev' && 'dev' || 'dev' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # Fetch at least the last 2 commits to ensure `HEAD^` exists

    - name: Set environment variables based on branch
      id: set-env
      run: |
        echo "API_KEY=${{ secrets.NEW_RELIC_API_KEY }}" >> $GITHUB_ENV
        echo "API_ENDPOINT=${{ secrets.NEW_RELIC_API_ENDPOINT }}" >> $GITHUB_ENV
        echo "MONITOR_UUID_TEACHER=${{ secrets.NEW_RELIC_MONITOR_UUID_TEACHER }}" >> $GITHUB_ENV
        echo "MONITOR_UUID_STUDENT=${{ secrets.NEW_RELIC_MONITOR_UUID_STUDENT }}" >> $GITHUB_ENV

    - name: Updating the scripts in Monitors
      run: |
        update_script() {
          local file_path="$1"
          local monitor_uuid="$2"
          
          if [ ! -f "$file_path" ]; then
            echo "Error: Script file does not exist: $file_path"
            exit 1
          fi

          base64_encoded=$(base64 -w 0 "$file_path")
          script_payload="{\"scriptText\":\"$base64_encoded\"}"

          # Capture both the response body and the HTTP status code.
          # -s = silent mode
          # -w "%{http_code}" = write out the HTTP status code
          # -o /tmp/monitor_update_response = write the actual response body to a file
          response_status=$(curl -s -w "%{http_code}" -o /tmp/monitor_update_response \
            -X PUT \
            -H "Api-Key:$API_KEY" \
            -H 'Content-Type: application/json' \
            "$API_ENDPOINT/v3/monitors/$monitor_uuid/script" \
            -d "$script_payload")

          if [ "$response_status" -ge 200 ] && [ "$response_status" -lt 300 ]; then
            echo "Synthetic Monitor script for $file_path and monitor id $monitor_uuid updated successfully."
          else
            echo "Error: Failed to update the Synthetic Monitor script for $file_path"
            echo "HTTP Status Code: $response_status"
            echo "Response Body:"
            cat /tmp/monitor_update_response
            exit 1
          fi    
        }

        # Check if seleniumScriptTeacher.js was modified
        if git diff --name-only HEAD^ HEAD | grep -q "seleniumScriptTeacher.js"; then
          echo "Updating seleniumScriptTeacher.js..."
          update_script "./seleniumScriptTeacher.js" "$MONITOR_UUID_TEACHER"
        fi

        # Check if seleniumScriptStudent.js was modified
        if git diff --name-only HEAD^ HEAD | grep -q "seleniumScriptStudent.js"; then
          echo "Updating seleniumScriptStudent.js..."
          update_script "./seleniumScriptStudent.js" "$MONITOR_UUID_STUDENT"
        fi
