name: Update New Relic Synthetic Monitor Script

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the workflow on

jobs:
  update-synthetic-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Choose the appropriate Node.js version

    - name: Check if package.json exists and install dependencies
      run: |
        if [ -f "package.json" ]; then
          npm install
        else
          echo "No package.json found, skipping npm install."
        fi

    - name: Get New Relic API key and Monitor ID from secrets
      run: |
        echo "NEW_RELIC_API_KEY=${{ secrets.NEW_RELIC_API_KEY }}" >> $GITHUB_ENV
        echo "MONITOR_ID=${{ secrets.MONITOR_ID }}" >> $GITHUB_ENV

    - name: Update New Relic Synthetics monitor script
      run: |
        set -e  # Exit immediately if a command fails
        
        # Ensure the script exists
        if [ ! -f "scripts/seleniumScriptTeacher.js" ]; then
          echo "Error: New Relic script file not found."
          exit 1
        fi
        
        echo "Updating New Relic Synthetic monitor script..."
        
        # Attempt to update the script
        response=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
          https://synthetics.newrelic.com/synthetics/api/v3/monitors/${{ env.MONITOR_ID }}/script \
          -H "X-Api-Key:${{ env.NEW_RELIC_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d @scripts/seleniumScriptTeacher.js)
        
        # Check for HTTP status code 2xx (successful request)
        if [[ "$response" -lt 200 || "$response" -ge 300 ]]; then
          echo "Error: Failed to update New Relic Synthetic script. HTTP Status: $response"
          exit 1
        fi
        
        echo "Script updated successfully. HTTP Status: $response"

    - name: Confirm update success
      run: echo "Script update process completed."
