name: Update New Relic Synthetic Monitor Script

on:
  push:
    paths:
      - seleniumScriptTeacher.js

jobs:
  update-monitor-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Base64 encode script
      id: encode-script
      run: |
        script_path="./seleniumScriptTeacher.js"
        if [ ! -f "$script_path" ]; then
          echo "Error: Script file does not exist: $script_path"
          exit 1
        fi
        base64Encoded=$(base64 -w 0 "$script_path") 
        echo "::set-output name=encoded-script::$base64Encoded"

    - name: Update Synthetic Monitor Script
      env:
        API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        MONITOR_UUID: ${{ secrets.NEW_RELIC_MONITOR_UUID }}
        API_ENDPOINT: https://synthetics.newrelic.com/synthetics/api
      run: |
        SCRIPT_PAYLOAD="{\"scriptText\":\"${{ steps.encode-script.outputs.encoded-script }}\"}"

        curl -v -X PUT \
          -H "Api-Key:$API_KEY" \
          -H 'Content-Type: application/json' \
          "$API_ENDPOINT/v3/monitors/$MONITOR_UUID/script" \
          -d "$SCRIPT_PAYLOAD"

        if [ $? -ne 0 ]; then
          echo "Error: Failed to update the Synthetic Monitor script."
          exit 1
        fi

        echo "Synthetic Monitor script updated successfully."
