name: CI/CD Pipeline with Manual Approval

on:
  push:
    branches:
      - main
      - dev
      - qa

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Build Process
        run: echo "Building the project..."

      - name: Build Completed
        run: echo "Build process completed successfully!"

      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          # Provide GitHub usernames or a single user if you're on a free plan.
          # If you need multiple approvals, separate with commas and set minimum-approvals accordingly.
          approvers: aaryanCompro
          minimum-approvals: 1
          issue-title: "Manual Approval Required for SAM Deploy"
          issue-body: "Please comment 'Approved' (or 'Denied') on this issue. The deploy step will proceed only upon approval."

      - name: Deploy to AWS
        run: echo "Deploying application after manual approval..."
