name: CI/CD Pipeline with Manual Approval

on:
  push:
    branches:
      - main
      - dev
      - qa
      - stage

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Build Process
        run: echo "Building the project..."

      - name: Build Completed
        run: echo "Build process completed successfully!"

  deploy:
    name: Deploy Job (Requires Manual Approval)
    runs-on: ubuntu-latest
    needs: build  # Waits for 'build' job to finish
    environment: qa  # Triggers manual approval
    steps:
      - name: Deployment Step
        run: echo "Deploying application after manual approval..."

      - name: Deployment Completed
        run: echo "Deployment successful!"
