name: CI/CD Pipeline with Manual Approval

on:
  push:
    branches:
      - main
      - dev
      - qa

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Build Process
        run: echo "Building the project..."

      - name: Build Completed
        run: echo "Build process completed successfully!"

  approval:
    name: Await Manual Approval
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Approval
        uses: reviewdog/action-wait-for-approval@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          approval_type: "comment"
          approvers: "aaryanCompro"
          timeout: 3600  # Timeout after 1 hour (3600 seconds)

  deploy:
    name: Deploy to AWS
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deploying application after manual approval..."
